Update Redis Client
kubedb/db-client-go pull request #48
Opened 2023-01-03 10:55 UTC by Shaad7

Signed-off-by: Shaad7 <abdullah.alshaad@appscode.com>

2023-01-05 09:46 UTC, pkbhowmick requested changes

2023-01-05 09:46 UTC, pkbhowmick commented on redis/kubedb_client_builder.go
> +		DialTimeout:     15 * time.Second,
Use constants

2023-01-05 10:12 UTC, pkbhowmick commented on redissentinel/kubedb_client_builder.go
> +	err := o.kc.Get(context.TODO(), client.ObjectKey{Namespace: o.db.Namespace, Name: o.db.CertificateName(api.RedisClientCert)}, &sec)
what about taking context in method param and then use in here?

2023-01-05 12:22 UTC, pkbhowmick approved these changes
LGTM!

2023-01-09 10:13 UTC, heheh13 approved these changes
LGTM!

2023-01-09 10:36 UTC, merged