Add tls for Pgpool client
kubedb/db-client-go pull request #99
Opened 2024-04-25 10:34 UTC by MobarakHsn

2024-04-25 13:30 UTC, souravbiswassanto requested changes

2024-04-25 13:30 UTC, souravbiswassanto commented on pgpool/kubedb_client_builder.go
> +		return "", fmt.Errorf("DB basic auth is not found for backend PostgreSQL %v/%v", o.pgpool.Namespace, o.pgpool.Name)
If client want to authenticate using certificate, then password has no significance. In this case user is allowed to not have auth secret. So you should only reject if bot (username,password) and (client cert) is not provided.

2024-04-25 13:45 UTC, souravbiswassanto approved these changes

2024-04-26 05:56 UTC, souravbiswassanto approved these changes

2024-04-26 09:54 UTC, ArnobKumarSaha approved these changes

2024-04-26 09:54 UTC, merged